# Generated by Django 4.1.7 on 2023-02-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="url",
            field=models.ImageField(default="test.jpg", upload_to=None),
        ),
    ]
